=== obercraft/deathcrawl/src/main/resources/cards/cards.dtd
<?xml encoding="UTF-8"?>

        <!ELEMENT cards (card)+>
        <!ELEMENT card (name|type|deck?|hits?|damage?|skill?|threat?|experience?|gold?|command?|usage-command?|uses?|starting-cards?|keywords?|effects?|text?|flavor?)*>

        <!ELEMENT name (#PCDATA)>
        <!ATTLIST name
                uniqueId CDATA "">

        <!ELEMENT hits (#PCDATA)>
        <!ELEMENT type (#PCDATA)>
        <!ELEMENT deck (#PCDATA)>
        <!ELEMENT damage (#PCDATA)>
        <!ELEMENT skill (#PCDATA)>
        <!ELEMENT threat (#PCDATA)>
        <!ELEMENT experience (#PCDATA)>
        <!ELEMENT gold (#PCDATA)>

        <!ELEMENT command (#PCDATA)>
        <!ELEMENT usage-command (#PCDATA)>
        <!ELEMENT uses (#PCDATA)>
        <!ELEMENT keywords (#PCDATA)>
        <!ELEMENT starting-cards (#PCDATA)>
        <!ELEMENT text (#PCDATA)>
        <!ELEMENT flavor (#PCDATA)>

        <!ELEMENT effects (effect)+>
        <!ELEMENT effect (#PCDATA)>
        <!ATTLIST effect event CDATA "startturn">

=== obercraft/deathcrawl/src/main/resources/cards/cards.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cards SYSTEM "cards.dtd">
<cards>
    <card>
        <name>Knife</name>
        <type>item</type>
        <damage>1</damage>
        <command>attack</command>
        <keywords>simple,weapon</keywords>
    </card>
    <card>
        <name>Throwing Knife</name>
        <type>item</type>
        <damage>1</damage>
        <command>attack</command>
        <keywords>simple,weapon,ranged</keywords>
    </card>
    <card>
        <name>Magic Missile</name>
        <type>spell</type>
        <command>random_attack_many 3 1</command>
        <keywords>wizard</keywords>
    </card>
</cards>

=== obercraft/deathcrawl/src/main/resources/cards/monsters.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE cards SYSTEM "cards.dtd">
<cards>
    <card>
        <name uniqueId="Thief">Kobold</name>
        <type>Monster</type>
        <hits>3</hits>
        <damage>1</damage>
        <experience>1</experience>
        <gold>1</gold>
        <flavor>A Kobold!</flavor>
    </card>

    <card>
        <name uniqueId="Thief">Goblin</name>
        <type>Monster</type>
        <hits>4</hits>
        <damage>2</damage>
        <experience>2</experience>
        <gold>1</gold>
        <flavor>A Goblin!</flavor>
    </card>

</cards>
