=== obercraft/deathcrawl/src/main/resources/world/world.dtd
<?xml encoding="UTF-8"?>

        <!ELEMENT world (terrains|sites)*>

        <!ELEMENT terrains (terrain)*>

        <!ELEMENT sites (site)*>

        <!ELEMENT site (encounter)*>
        <!ATTLIST site
                  name  CDATA "">
        <!ATTLIST site
                terrain CDATA "">

        <!ELEMENT terrain (encounter)*>
        <!ATTLIST terrain
                  name  CDATA "">
        <!ATTLIST terrain
                left  CDATA "">
        <!ATTLIST terrain
                right  CDATA "">

        <!ATTLIST terrain
                move  CDATA "">

        <!ATTLIST terrain
                tile  CDATA "">

        <!ELEMENT encounter (#PCDATA)>
        <!ATTLIST encounter
                warning  CDATA "">

=== obercraft/deathcrawl/src/main/resources/world/world.xml
<!-- HOWL, FLUTTER, ROAR, PATTER, SLITHER -->
<!-- SMOKE                   RUINS                      DANK                    BONES -->
<!-- LOST CITY STATUE ALTAR VAULT POOL LOST CASTLE HOARD LAIR CAIRNS SHRINE -->

<!DOCTYPE world SYSTEM "world.dtd">
<world>
    <terrains>
        <terrain name="Water" left="-2.0" right="-0.8" move="4"></terrain>
        <terrain name="Desert" left="-8.0" right="-0.6" move="4"></terrain>
        <terrain name="Caves" left="-0.6" right="-0.5" move="2"></terrain>
        <terrain name="Valley" left="-0.5" right="0.3" move="1">
            <encounter warning="howl">Wolf</encounter>
            <encounter warning="flutter">Wolf</encounter>
            <encounter warning="stink">Wolf</encounter>
            <encounter warning="dank">Wolf</encounter>
        </terrain>
        <terrain name="Woods" left="0.3" right="0.5" move="2"></terrain>
        <terrain name="Hill" left="0.5" right="0.7" ></terrain>
        <terrain name="Mountain" left="0.7" right="2.0"></terrain>
    </terrains>
    <sites>
        <site name="altar" terrain="valley, hill">
            <encounter warning="*">demon</encounter>
        </site>
    </sites>

</world>
