=== obercraft/deathcrawl/src/main/resources/encounters/encounter-matrix.dtd
<?xml encoding="UTF-8"?>

        <!ELEMENT encounter-matrix (encounters)+>

        <!ELEMENT encounters (site|land)+>

        <!ELEMENT site (encounter)+>
        <!ATTLIST site
                  name  CDATA "">

        <!ELEMENT land (encounter)+>
        <!ATTLIST land
                  name  CDATA "">

        <!ELEMENT encounter (#PCDATA)>
        <!ATTLIST encounter
                warning  CDATA "">

=== obercraft/deathcrawl/src/main/resources/encounters/encounter-matrix.xml
<!-- HOWL, FLUTTER, ROAR, PATTER, SLITHER -->
<!-- SMOKE                   RUINS                      DANK                    BONES -->
<!-- LOST CITY STATUE ALTAR VAULT POOL LOST CASTLE HOARD LAIR CAIRNS SHRINE -->
<!DOCTYPE encounter-matrix SYSTEM "encounter-matrix.dtd">
<encounter-matrix>
    <encounters>
        <land name="valley">
            <encounter warning="howl">Wolf</encounter>
            <encounter warning="flutter">Wolf</encounter>
            <encounter warning="stink">Wolf</encounter>
            <encounter warning="dank">Wolf</encounter>
        </land>
        <site name="altar">
            <encounter warning="*">demon</encounter>
        </site>
    </encounters>
</encounter-matrix>
